// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebV1.Capas.Modelo.Data;

#nullable disable

namespace WebV1.Migrations
{
    [DbContext(typeof(WevApiContext))]
    [Migration("20230610155118_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebV1.Capas.Modelo.Entidad.Usuario", b =>
                {
                    b.Property<int>("IdUSuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDUSUARIO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUSuario"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("APELLIDOS");

                    b.Property<int>("Dieta")
                        .HasColumnType("int");

                    b.Property<string>("Edad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EDAD");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FOTO");

                    b.Property<int?>("MonitorId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOMBRE");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Peso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PESO");

                    b.Property<int>("Tabla")
                        .HasColumnType("int");

                    b.Property<bool>("Tienemonitor")
                        .HasColumnType("bit")
                        .HasColumnName("TIENEMONITOR");

                    b.HasKey("IdUSuario");

                    b.HasIndex("Dieta");

                    b.HasIndex("MonitorId");

                    b.HasIndex("Tabla");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("WebV1.Capas.Modelo.Monitores", b =>
                {
                    b.Property<int>("IdMonitor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDMONITOR");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMonitor"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("APELLIDOS");

                    b.Property<int>("Dieta")
                        .HasColumnType("int");

                    b.Property<string>("Edad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EDAD");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FOTO");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOMBRE");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Peso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PESO");

                    b.Property<int>("Tabla")
                        .HasColumnType("int");

                    b.HasKey("IdMonitor");

                    b.HasIndex("Dieta");

                    b.HasIndex("Tabla");

                    b.ToTable("Monitor");
                });

            modelBuilder.Entity("WebV1.Seguridad.Models.Dieta", b =>
                {
                    b.Property<int>("IdDieta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDDIETA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDieta"));

                    b.Property<string>("Domingo1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOMINGO1");

                    b.Property<string>("Domingo2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOMINGO2");

                    b.Property<string>("Domingo3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOMINGO3");

                    b.Property<string>("Domingo4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOMINGO4");

                    b.Property<string>("Domingo5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOMINGO5");

                    b.Property<string>("Domingo6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOMINGO6");

                    b.Property<string>("Domingo7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOMINGO7");

                    b.Property<string>("Domingo8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOMINGO8");

                    b.Property<string>("Horario1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HORARIO1");

                    b.Property<string>("Horario2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HORARIO2");

                    b.Property<string>("Horario3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HORARIO3");

                    b.Property<string>("Horario4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HORARIO4");

                    b.Property<string>("Horario5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HORARIO5");

                    b.Property<string>("Horario6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HORARIO6");

                    b.Property<string>("Horario7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HORARIO7");

                    b.Property<string>("Horario8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HORARIO8");

                    b.Property<string>("Jueves1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JUEVES1");

                    b.Property<string>("Jueves2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JUEVES2");

                    b.Property<string>("Jueves3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JUEVES3");

                    b.Property<string>("Jueves4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JUEVES4");

                    b.Property<string>("Jueves5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JUEVES5");

                    b.Property<string>("Jueves6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JUEVES6");

                    b.Property<string>("Jueves7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JUEVES7");

                    b.Property<string>("Jueves8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JUEVES8");

                    b.Property<string>("Lunes1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LUNES1");

                    b.Property<string>("Lunes2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LUNES2");

                    b.Property<string>("Lunes3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LUNES3");

                    b.Property<string>("Lunes4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LUNES4");

                    b.Property<string>("Lunes5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LUNES5");

                    b.Property<string>("Lunes6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LUNES6");

                    b.Property<string>("Lunes7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LUNES7");

                    b.Property<string>("Lunes8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LUNES8");

                    b.Property<string>("Martes1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MARTES1");

                    b.Property<string>("Martes2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MARTES2");

                    b.Property<string>("Martes3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MARTES3");

                    b.Property<string>("Martes4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MARTES4");

                    b.Property<string>("Martes5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MARTES5");

                    b.Property<string>("Martes6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MARTES6");

                    b.Property<string>("Martes7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MARTES7");

                    b.Property<string>("Martes8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MARTES8");

                    b.Property<string>("Miercoles1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MIERCOLES1");

                    b.Property<string>("Miercoles2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MIERCOLES2");

                    b.Property<string>("Miercoles3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MIERCOLES3");

                    b.Property<string>("Miercoles4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MIERCOLES4");

                    b.Property<string>("Miercoles5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MIERCOLES5");

                    b.Property<string>("Miercoles6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MIERCOLES6");

                    b.Property<string>("Miercoles7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MIERCOLES7");

                    b.Property<string>("Miercoles8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MIERCOLES8");

                    b.Property<string>("Sabado1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SABADO1");

                    b.Property<string>("Sabado2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SABADO2");

                    b.Property<string>("Sabado3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SABADO3");

                    b.Property<string>("Sabado4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SABADO4");

                    b.Property<string>("Sabado5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SABADO5");

                    b.Property<string>("Sabado6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SABADO6");

                    b.Property<string>("Sabado7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SABADO7");

                    b.Property<string>("Sabado8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SABADO8");

                    b.Property<string>("Viernes1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VIERNES1");

                    b.Property<string>("Viernes2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VIERNES2");

                    b.Property<string>("Viernes3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VIERNES3");

                    b.Property<string>("Viernes4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VIERNES4");

                    b.Property<string>("Viernes5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VIERNES5");

                    b.Property<string>("Viernes6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VIERNES6");

                    b.Property<string>("Viernes7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VIERNES7");

                    b.Property<string>("Viernes8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VIERNES8");

                    b.HasKey("IdDieta");

                    b.ToTable("Dieta");
                });

            modelBuilder.Entity("WebV1.Seguridad.Models.Ejercicios", b =>
                {
                    b.Property<int>("IdEjercicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDEJERCICIOS");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEjercicio"));

                    b.HasKey("IdEjercicio");

                    b.ToTable("Ejercicio");
                });

            modelBuilder.Entity("WebV1.Seguridad.Models.Tabla", b =>
                {
                    b.Property<int>("IdTabla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDTABLA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTabla"));

                    b.Property<string>("Domingo1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOMINGO1");

                    b.Property<string>("Domingo2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOMINGO2");

                    b.Property<string>("Domingo3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOMINGO3");

                    b.Property<string>("Domingo4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOMINGO4");

                    b.Property<string>("Domingo5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOMINGO5");

                    b.Property<string>("Domingo6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOMINGO6");

                    b.Property<string>("Domingo7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOMINGO7");

                    b.Property<string>("Domingo8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOMINGO8");

                    b.Property<string>("Horario1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HORARIO1");

                    b.Property<string>("Horario2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HORARIO2");

                    b.Property<string>("Horario3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HORARIO3");

                    b.Property<string>("Horario4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HORARIO4");

                    b.Property<string>("Horario5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HORARIO5");

                    b.Property<string>("Horario6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HORARIO6");

                    b.Property<string>("Horario7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HORARIO7");

                    b.Property<string>("Horario8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HORARIO8");

                    b.Property<string>("Jueves1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JUEVES1");

                    b.Property<string>("Jueves2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JUEVES2");

                    b.Property<string>("Jueves3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JUEVES3");

                    b.Property<string>("Jueves4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JUEVES4");

                    b.Property<string>("Jueves5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JUEVES5");

                    b.Property<string>("Jueves6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JUEVES6");

                    b.Property<string>("Jueves7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JUEVES7");

                    b.Property<string>("Jueves8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JUEVES8");

                    b.Property<string>("Lunes1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LUNES1");

                    b.Property<string>("Lunes2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LUNES2");

                    b.Property<string>("Lunes3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LUNES3");

                    b.Property<string>("Lunes4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LUNES4");

                    b.Property<string>("Lunes5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LUNES5");

                    b.Property<string>("Lunes6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LUNES6");

                    b.Property<string>("Lunes7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LUNES7");

                    b.Property<string>("Lunes8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LUNES8");

                    b.Property<string>("Martes1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MARTES1");

                    b.Property<string>("Martes2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MARTES2");

                    b.Property<string>("Martes3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MARTES3");

                    b.Property<string>("Martes4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MARTES4");

                    b.Property<string>("Martes5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MARTES5");

                    b.Property<string>("Martes6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MARTES6");

                    b.Property<string>("Martes7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MARTES7");

                    b.Property<string>("Martes8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MARTES8");

                    b.Property<string>("Miercoles1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MIERCOLES1");

                    b.Property<string>("Miercoles2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MIERCOLES2");

                    b.Property<string>("Miercoles3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MIERCOLES3");

                    b.Property<string>("Miercoles4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MIERCOLES4");

                    b.Property<string>("Miercoles5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MIERCOLES5");

                    b.Property<string>("Miercoles6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MIERCOLES6");

                    b.Property<string>("Miercoles7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MIERCOLES7");

                    b.Property<string>("Miercoles8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MIERCOLES8");

                    b.Property<string>("Sabado1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SABADO1");

                    b.Property<string>("Sabado2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SABADO2");

                    b.Property<string>("Sabado3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SABADO3");

                    b.Property<string>("Sabado4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SABADO4");

                    b.Property<string>("Sabado5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SABADO5");

                    b.Property<string>("Sabado6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SABADO6");

                    b.Property<string>("Sabado7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SABADO7");

                    b.Property<string>("Sabado8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SABADO8");

                    b.Property<string>("Viernes1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VIERNES1");

                    b.Property<string>("Viernes2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VIERNES2");

                    b.Property<string>("Viernes3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VIERNES3");

                    b.Property<string>("Viernes4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VIERNES4");

                    b.Property<string>("Viernes5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VIERNES5");

                    b.Property<string>("Viernes6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VIERNES6");

                    b.Property<string>("Viernes7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VIERNES7");

                    b.Property<string>("Viernes8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VIERNES8");

                    b.HasKey("IdTabla");

                    b.ToTable("Tabla");
                });

            modelBuilder.Entity("WebV1.Capas.Modelo.Entidad.Usuario", b =>
                {
                    b.HasOne("WebV1.Seguridad.Models.Dieta", "dieta")
                        .WithMany()
                        .HasForeignKey("Dieta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebV1.Capas.Modelo.Monitores", "Monitor")
                        .WithMany("ListaDeUSuarios")
                        .HasForeignKey("MonitorId");

                    b.HasOne("WebV1.Seguridad.Models.Tabla", "tabla")
                        .WithMany()
                        .HasForeignKey("Tabla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monitor");

                    b.Navigation("dieta");

                    b.Navigation("tabla");
                });

            modelBuilder.Entity("WebV1.Capas.Modelo.Monitores", b =>
                {
                    b.HasOne("WebV1.Seguridad.Models.Dieta", "dieta")
                        .WithMany()
                        .HasForeignKey("Dieta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebV1.Seguridad.Models.Tabla", "tabla")
                        .WithMany()
                        .HasForeignKey("Tabla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dieta");

                    b.Navigation("tabla");
                });

            modelBuilder.Entity("WebV1.Capas.Modelo.Monitores", b =>
                {
                    b.Navigation("ListaDeUSuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
